name: sicilia_mafia
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.8
  flutter_bloc:
  freezed: ^0.15.0+1
  get_it: ^7.2.0
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.5
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  json_serializable:
  group_button: ^3.3.1
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.4
  freezed_annotation: ^0.15.0
  new_gradient_app_bar: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - locales/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
